site_name: Xailient Docs
nav:
    - About Xailient FaceSDK: XailientFaceSDK.md
    - Getting Started: getting_started.md
    - Installation: installation.md
    - Sample Code: sample_code.md
theme: 
    name: 'material'
    logo: 'img/logo.png'
    favicon: 'img/favicon.png'
extra_css:
- 'stylesheets/extra.css'
markdown_extensions:
  - admonition